### ISSUE TITLE
Streaming Tokens

### ISSUE THREAD

**Issue by di-wu** [DepartureLabsIC/non-fungible-token#16]
When an asset is divided in parts you can query them with `http_request`. In the response you get a `streaming_strategy` to get the chunks one-by-one. Yet this seems to be very tedious.

Is there a better way of doing this? Maybe convert it to an `Iter` with `next`?

I just need this for tests, it would probably not be used by other canisters.

```motoko
// Get first part of the asset (index = 0).
let p0 = A.get("a");
switch (p0.streaming_strategy) {
    case (null) { assert(false) }; // There should be a part 2.
    case (?#Callback(cb)) {
        assert(cb.token.index == 1);
        let p1 = await cb.callback(cb.token);
        switch (p1.token) {
            case (null) { assert(false) }; // There should be a part 3.
            case (? p1t) {
                assert(p1t.index == 2);
                let p2 = await cb.callback(p1t);
                assert(p2.token == null); // Last part.
            };
        };
    };
};
```

**Comment by di-wu** [comment]
More info about the `http_request` interface:
https://github.com/dfinity/agent-rs/blob/main/ic-utils/src/interfaces/http_request.rs

**Comment by SuddenlyHazel** [comment]
https://github.com/DepartureLabsIC/non-fungible-token/blob/97589c535e50ee20bd76c7fe7ceddb94c5c7726a/src/main.mo#L840

We've implemented the streaming callback already, but I don't think we can make it much more elegant since the design is spec by `ic-proxy`. What issues are you hitting with the way things are working today?

**Comment by di-wu** [comment]
There are currently some inconsistencies in the current implementation.

`http_request_streaming_callback` only checks for NFTs. 
Yet the callback is also used as a callback for assets (indirectly through [`_handleLargeContent`](https://github.com/DepartureLabsIC/non-fungible-token/blob/97589c535e50ee20bd76c7fe7ceddb94c5c7726a/src/main.mo#L783-L803)).

https://github.com/DepartureLabsIC/non-fungible-token/blob/97589c535e50ee20bd76c7fe7ceddb94c5c7726a/src/main.mo#L833-L836

AFAIK this breaks asset streaming, if I understand the `ic-proxy` 'spec' correctly.

**Comment by SuddenlyHazel** [comment]
Oh dang good catch. I could have sworn I accounted for that, but clearly too much code cave on my end lol.
