### ISSUE TITLE
Inconsistency in ownerOf after transfer

### ISSUE THREAD

**Issue by silimarius** [DepartureLabsIC/non-fungible-token#28]
Hi guys! First of all I'd like to say that I really like this implementation.

In `token.mo` you use two hash maps to keep track of the ownership of the tokens, but when calling `transfer` only `ownerToNFT` gets updated, while `nftToOwner` remains unchanged, thus the next call to `ownerOf` will return the old owner.

**Comment by di-wu** [comment]
Hi @silimarius! Thank you for reporting this! 💯
